config:
  info: "config info for dev(333)"
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/remote_operation?useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&allowMultiQueries=true
    username: root
    password: root
# MybatisPlus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://thingcom:123456@localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
